"""
This script contains the denisty (g/cm2) per all the categories of FoodSeg103.
The creation of this file has been done manually, a change in the dataset may result in errors.
"""
DENSITY_TABLE = {
    "candy":                0.40,
    "egg tart":             0.32,
    "french fries":         0.18,
    "chocolate":            0.55,
    "biscuit":              0.35,
    "popcorn":              0.05,
    "pudding":              0.30,
    "ice cream":            0.25,
    "cheese butter":        0.60,
    "cake":                 0.28,
    "wine":                 0.10,  
    "milkshake":            0.12,
    "coffee":               0.08,
    "juice":                0.10,
    "milk":                 0.10,
    "tea":                  0.08,
    "almond":               0.45,
    "red beans":            0.40,
    "cashew":               0.45,
    "dried cranberries":    0.40,
    "soy":                  0.38,
    "walnut":               0.42,
    "peanut":               0.45,
    "egg":                  0.12,  
    "apple":                0.13,
    "date":                 0.36,
    "apricot":              0.13,
    "avocado":              0.17,
    "banana":               0.15,
    "strawberry":           0.11,
    "cherry":               0.12,
    "blueberry":            0.11,
    "raspberry":            0.10,
    "mango":                0.14,
    "olives":               0.20,
    "peach":                0.13,
    "lemon":                0.12,
    "pear":                 0.13,
    "fig":                  0.14,
    "pineapple":            0.14,
    "grape":                0.11,
    "kiwi":                 0.14,
    "melon":                0.10,
    "orange":               0.12,
    "watermelon":           0.09,
    "steak":                0.55,
    "pork":                 0.50,
    "chicken duck":         0.45,
    "sausage":              0.42,
    "fried meat":           0.40,
    "lamb":                 0.50,
    "sauce":                0.18,
    "crab":                 0.45,
    "fish":                 0.42,
    "shellfish":            0.40,
    "shrimp":               0.38,
    "soup":                 0.10,
    "bread":                0.23,
    "corn":                 0.22,
    "hamburg":              0.30,
    "pizza":                0.30,
    "hanamaki baozi":       0.25,
    "wonton dumplings":     0.30,
    "pasta":                0.24,
    "noodles":              0.22,
    "rice":                 0.20,
    "pie":                  0.32,
    "tofu":                 0.17,
    "eggplant":             0.13,
    "potato":               0.18,
    "garlic":               0.22,
    "cauliflower":          0.10,
    "tomato":               0.12,
    "kelp":                 0.08,
    "seaweed":              0.05,
    "spring onion":         0.06,
    "rape":                 0.06,
    "ginger":               0.22,
    "okra":                 0.12,
    "lettuce":              0.05,
    "pumpkin":              0.14,
    "cucumber":             0.11,
    "white radish":         0.14,
    "carrot":               0.15,
    "asparagus":            0.10,
    "bamboo shoots":        0.12,
    "broccoli":             0.09,
    "celery stick":         0.07,
    "cilantro mint":        0.05,
    "snow peas":            0.09,
    "cabbage":              0.08,
    "bean sprouts":         0.06,
    "onion":                0.14,
    "pepper":               0.12,
    "green beans":          0.11,
    "French beans":         0.11,
    "king oyster mushroom": 0.09,
    "shiitake":             0.08,
    "enoki mushroom":       0.07,
    "oyster mushroom":      0.07,
    "white button mushroom":0.07,
    "salad":                0.06,
    "other ingredients":    0.20,
}
