"""
This script contains the density (g/cm2) per all the categories of FoodSeg103 + .
The creation of this file has been done manually, a change in the dataset may result in errors.
"""
DENSITY_TABLE = {
    "candy":                4.0,
    "egg tart":             3.2,
    "french fries":         1.8,
    "chocolate":            5.5,
    "biscuit":              3.5,
    "popcorn":              0.5,
    "pudding":              3.0,
    "ice cream":            2.5,
    "cheese butter":        6.0,
    "cake":                 2.8,
    "wine":                 1.0,
    "milkshake":            1.2,
    "coffee":               0.8,
    "juice":                1.0,
    "milk":                 1.0,
    "tea":                  0.8,
    "almond":               4.5,
    "red beans":            4.0,
    "cashew":               4.5,
    "dried cranberries":    4.0,
    "soy":                  3.8,
    "walnut":               4.2,
    "peanut":               4.5,
    "egg":                  1.2,
    "apple":                1.3,
    "date":                 3.6,
    "apricot":              1.3,
    "avocado":              1.7,
    "banana":               1.5,
    "strawberry":           1.1,
    "cherry":               1.2,
    "blueberry":            1.1,
    "raspberry":            1.0,
    "mango":                1.4,
    "olives":               2.0,
    "peach":                1.3,
    "lemon":                1.2,
    "pear":                 1.3,
    "fig":                  1.4,
    "pineapple":            1.4,
    "grape":                1.1,
    "kiwi":                 1.4,
    "melon":                1.0,
    "orange":               1.2,
    "watermelon":           0.9,
    "steak":                5.5,
    "pork":                 5.0,
    "chicken duck":         4.5,
    "sausage":              4.2,
    "fried meat":           4.0,
    "lamb":                 5.0,
    "sauce":                1.8,
    "crab":                 4.5,
    "fish":                 4.2,
    "shellfish":            4.0,
    "shrimp":               3.8,
    "soup":                 1.0,
    "bread":                2.3,
    "corn":                 2.2,
    "hamburg":              3.0,
    "pizza":                3.0,
    "hanamaki baozi":       2.5,
    "wonton dumplings":     3.0,
    "pasta":                2.4,
    "noodles":              2.2,
    "rice":                 2.0,
    "pie":                  3.2,
    "tofu":                 1.7,
    "eggplant":             1.3,
    "potato":               1.8,
    "garlic":               2.2,
    "cauliflower":          1.0,
    "tomato":               1.2,
    "kelp":                 0.8,
    "seaweed":              0.5,
    "spring onion":         0.6,
    "rape":                 0.6,
    "ginger":               2.2,
    "okra":                 1.2,
    "lettuce":              0.5,
    "pumpkin":              1.4,
    "cucumber":             1.1,
    "white radish":         1.4,
    "carrot":               1.5,
    "asparagus":            1.0,
    "bamboo shoots":        1.2,
    "broccoli":             0.9,
    "celery stick":         0.7,
    "cilantro mint":        0.5,
    "snow peas":            0.9,
    "cabbage":              0.8,
    "bean sprouts":         0.6,
    "onion":                1.4,
    "pepper":               1.2,
    "green beans":          1.1,
    "French beans":         1.1,
    "king oyster mushroom": 0.9,
    "shiitake":             0.8,
    "enoki mushroom":       0.7,
    "oyster mushroom":      0.7,
    "white button mushroom":0.7,
    "salad":                0.6,
    "other ingredients":    2.0,
}
